export const toolbox: string;
export const categories: string;
export const category: string;
export const activeCategory: string;
export const toolboxBricks: string;
export const mask: string;
export const maskItem: string;
export const froggyWrap: string;
export const froggy: string;
