import { createAsyncThunk, createListenerMiddleware, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../app/store';
import { Brick, BrickOutput, DragData, Offset } from '../types';
import { clone, deep_clone, distance_2d, for_each_brick, get_global_offset, get_id, is_container, to_id, update_path } from '../util';

export interface BrickState {
  blocks_offset: Offset,
  bricks: Brick[],
  toolbox: {
    categories: {[name: string]: Brick[]},
    activeCategory: string,
  },
  atomic_dropdown_menu: {[id: string]: {[name: string]: any}},
};

const initialState: BrickState = {
  bricks: [],
  blocks_offset: { x: 0, y: 0 },
  toolbox: {
    categories: {},
    activeCategory: "",
  },
  atomic_dropdown_menu: {},
};

export const brickSlice = createSlice({
  name: "brick",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setActiveToolbox: (state, action: PayloadAction<string>) => {
      state.toolbox.activeCategory = action.payload;
    },
    setBricks: (state, action: PayloadAction<Brick[]>) => {
      state.bricks = action.payload;
    },
    reset: (state, action: PayloadAction<BrickState>) => {
      return {
        ...action.payload,
        toolbox: {
          categories: Object.keys(action.payload.toolbox.categories).reduce(
            (m, i) => {
              m[i] = action.payload.toolbox.categories[i].map((j, idx) =>
                update_path(clone(j, true, false), [idx])
              );
              return m;
            },
            {}
          ),
          activeCategory: action.payload.toolbox.activeCategory,
        },
        bricks: action.payload.bricks
          .map((i) => clone(i))
          .map((i, idx) => update_path(i, [idx])),
      };
    },
    setBlocksOffset: (state, action: PayloadAction<Offset>) => {
      state.blocks_offset = action.payload;
    },
    changeBlocksOffsetBy: (state, action: PayloadAction<Offset>) => {
      state.blocks_offset.x += action.payload.x;
      state.blocks_offset.y += action.payload.y;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
  },
});

export const {
  setBlocksOffset,
  changeBlocksOffsetBy,
  reset,
  setActiveToolbox,
  setBricks,
} = brickSlice.actions;

export const selectBlocksOffset = (state: RootState) => {
  return state.brick.blocks_offset;
}

export const setBrickOffset = (
  bricks: Brick[],
  payload: { path: string[]; offset: Offset }
) => {
  const brick: Brick = payload.path.reduce((m, i) => m[i], bricks);
  brick.ui.offset = payload.offset;
};

export const removeRootBrickByIdx = (bricks: Brick[], payload: number) => {
  bricks.splice(payload, 1);
  bricks.forEach((i, idx) => update_path(i, [idx]));
};

export const insert = (
  bricks: Brick[],
  payload: { path: string[]; source: Brick }
) => {
  const brick = payload.source;
  if (!payload.path.length) {
    bricks.push(brick);
  } else {
    const parent: Brick = payload.path.reduce((m, i) => m[i], bricks);
    const t = parent.next;
    parent.next = brick;
    brick.next = t;
  }
};

export const detach = (
  bricks: Brick[],
  payload: { path: string[]; offset: Offset },
) => {
  const parent: Brick = payload.path
    .slice(0, -1)
    .reduce((m, i) => m[i], bricks);
  const brick: Brick = payload.path.reduce(
    (m, i) => m[i],
    bricks
  );
  const type = payload.path[payload.path.length - 1];
  if (type === "next") {
    parent.next = null;
    const new_brick = update_path(clone(brick), [bricks.length]);
    new_brick.ui.offset = payload.offset;
    bricks.push(new_brick);
  } else {
    // TODO
  }
};

export const selectAll = (state: RootState) => {
  return state.brick;
}

export const selectBricks = (state: RootState) => {
  return state.brick.bricks;
}

export default brickSlice.reducer;

  const brick_on_drag = (e) => {
    /*
    const drag_data = brick_drag_start_data;
    const id = drag_data.id;
    const brick_data = brick_id_to_data[id];
    if (!brick_is_dragging) {
      brick_is_dragging = true;
      brick_on_first_drag(e);
      return;
    }

    const offset = {
      x: drag_data.local_offset.x + e.pageX - drag_data.mouse_global_x,
      y: drag_data.local_offset.y + e.pageY - drag_data.mouse_global_y,
    };
    let workspace_needs_update = false;
    let needs_update_size = false;
    const active_brick_needs_removing =
      offset.x < -froggy_offset.x + toolbox_ref.current.clientWidth;
    if (active_brick_needs_removing != active_brick_needs_removing) {
      active_brick_needs_removing = active_brick_needs_removing;
      brick_id_to_data[id].ui.is_removing = active_brick_needs_removing;
    }
    const closest = inserting_candidates.reduce(
      (m, i) => {
        const current = brick_id_to_data[i];
        const parent = brick_id_to_data[current.ui.parent];
        const x1 = offset.x;
        const y1 = offset.y;
        const x2 =
          inserting_candidates_local_offset[i].x +
          (parent && parent.parts ? 15 : 0);
        const y2 =
          inserting_candidates_local_offset[i].y +
          (brick_data.output ? 0 : brick_id_to_size[i].h);
        const distance = distance_2d(x1, y1, x2, y2);
        if (distance < m.distance) {
          m.distance = distance;
          m.closest_brick_id = i;
        }
        return m;
      },
      {
        distance: Infinity,
        closest_brick_id: null,
      }
    );
    if (closest.distance < 15 && !active_brick_needs_removing) {
      if (!brick_is_inserting) {
        brick_is_inserting = true;

        const closest_brick = brick_id_to_data[closest.closest_brick_id];
        const tail = brick_id_to_data[active_brick_tail_id];
        if (brick_data.output) {
          if (closest_brick.inputs[0]) {
            detach_brick(closest_brick.inputs[0].id, undefined, {
              x: offset.x + 20,
              y: offset.y + 20,
            });
            needs_update_size = true;
          }
          closest_brick.inputs = [brick_data];
          brick_data.ui.parent = closest_brick.id;
        } else {
          tail.next = closest_brick.next;
          if (closest_brick.next) {
            closest_brick.next.prev = tail.id;
          }
          closest_brick.next = brick_data;
          brick_data.prev = closest_brick.id;
        }

        const root_id = closest_brick.root || closest_brick.id;
        for_each_brick(brick_data, tail, (i) => {
          i.ui.is_ghost = true;
          i.root = root_id;
        });
        brick_data.is_root = false;

        remove_root_brick(brick_data, false);
        brick_data.ui.offset.x = 0;
        brick_data.ui.offset.y = 0;

        workspace_needs_update = true;
      }
    } else {
      if (brick_is_inserting) {
        brick_is_inserting = false;
        if (!brick_data.is_root) {
          detach_brick(id, active_brick_tail_id);
        }
        workspace_needs_update = true;
      }
    }

    if (!brick_is_inserting) {
      let target = brick_data;
      if (brick_data.is_static) {
        target = get_ancestor(brick_id_to_data, brick_data);
      }
      target.ui.offset.x = offset.x;
      target.ui.offset.y = offset.y;
      if (target !== root_bricks[root_bricks.length - 1]) {
        remove_root_brick(target, false);
        root_bricks.push(target);
        workspace_needs_update = true;
      } else {
        brick_id_to_component[target.id].forceUpdate();
      }
    }

    // TODO
    */
  };